# CONFIGURATION FILE LOCATION ON YOUR SYSTEM:
# -------------------------------------------
# Defaults:
# ---------
#  Linux:   `$HOME/.config/television/config.toml`
#  macOS:   `$HOME/.config/television/config.toml`
#  Windows: `%APPDATA%\television\config.toml`
#
# XDG dirs:
# ---------
# You may use XDG_CONFIG_HOME if set on your system.
# In that case, television will expect the configuration file to be in:
# `$XDG_CONFIG_HOME/television/config.toml`
#

[ui]
theme = "television"
ui_scale = 100
frame_rate = 60
tick_rate = 50

# Whether to use nerd font icons in the UI
# This option requires a font patched with Nerd Font in order to properly
# display glyphs (see https://www.nerdfonts.com/ for more information)
use_nerd_font_icons = false

input_bar_position = "top"

# Show help by default
show_help_bar = false

# Show preview by default
show_preview_panel = true


[keybindings]
quit = ["esc", "ctrl-c"]
select_next_entry = ["tab", "down"]
select_prev_entry = ["backtab", "up"]
select_next_page = "pagedown"
select_prev_page = "pageup"
select_next_preview = "shift-right"
select_prev_preview = "shift-left"
select_next_run = "ctrl-n"
select_prev_run = "ctrl-b"
toggle_remote_control = "ctrl-z"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"
toggle_transition = "ctrl-t"
toggle_preview_commands = "ctrl-f"
toggle_run_commands = "ctrl-r"
toggle_logs = "ctrl-x"
toggle_preview = "ctrl-o"
scroll_preview_half_page_down = ["ctrl-d"]
scroll_preview_half_page_up = ["ctrl-u"]
scroll_log_down = "ctrl-right"
scroll_log_up = "ctrl-left"
toggle_selection_down = "shift-down"
toggle_selection_up = "shift-up"
confirm_selection = "enter"
copy_entry_to_clipboard = "ctrl-y"
select_entry = "enter"

# The shell integration feature allows you to use television as a picker for
# your shell commands(<CTRL-T>) and history (<CTRL-R>)
# E.g. typing `git checkout <CTRL-T>` will open television with a list of
# branches to choose from.

[shell_integration.commands]
# Add your commands here. Each key is a command that will trigger tv with the
# corresponding channel as value.
# Example: say you want the following prompts to trigger the following channels
# when pressing <CTRL-T>:
#          `git checkout` should trigger the `git-branches` channel
#          `ls`           should trigger the `dirs` channel
#          `cat`          should trigger the `files` channel
#
# You would add the following to your configuration file:
# ```
# [shell_integration.commands]
# "git checkout" = "git-branch"
# "ls" = "dirs"
# "cat" = "files"
# ```

# environment variables
"export" = "env"
"unset" = "env"

# dirs channel
"cd" = "dirs"
"ls" = "dirs"
"rmdir" = "dirs"

# files channel
"cat" = "files"
"less" = "files"
"head" = "files"
"tail" = "files"
"vim" = "files"
"bat" = "files"

# git-diff channel
"git add" = "git-diff"

# git-branch channel
"git checkout" = "git-branch"
"git branch -d" = "git-branch"

# docker-images channel
"docker run" = "docker-images"

# gitrepos channel
"nvim" = "git-repos"
